### ISSUE TITLE
A list of "research questions" along the way

### ISSUE THREAD

**Issue by ahussain3** [ahussain3/maya#2]
In this issue post any questions you think of along the way. You might not be able to address all of the immediately but it's good to have this list to look at for inspiration.

**Comment by ahussain3** [comment]
What is the demographic / socio-economic breakdown of people living in different social housing? Is there a dataset for this?

**Comment by initioterum** [comment]
How can social housing vary by region? What is the range in living standards?

Yes - what types of houses, how many people per household, what are their age ranges, how close together are social housing areas. What is the discrepancy in property values between social housing and other housing.

**Comment by initioterum** [comment]
What are the mechanisms for being allocated social housing? Does a person's background influence the type or standard of housing they are given?

**Comment by initioterum** [comment]
How can we operationalise the 'quality' of a given house? It'll be hard to draw conclusions on this without establishing this. I think this question will end up driving the kind of data that is sought

**Comment by initioterum** [comment]
- How long do applicants have to wait before being allocated a house in different regions, on average?
- What is the range, median and mean waiting time to be allocated a house?
- A comparison of the number of applicants on the waiting list to the council housing stock for an areas (occupied and unoccupied)
- Proportion of tenancy conversions from 'temporary' to 'secure' vs 'fixed-term' after 12 months
- Comparison of the repair policies in different councils (perhaps by timescale)
- Evictions/prosecutions on grounds of council house fraud
- Spending on council house fraud investigations

**Comment by ahussain3** [comment]
How has the number of people in social housing changed over time (and by area). I wonder if we can tell a "History of Modern Britain" just through the number of people in social housing over time.
